apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailer-app-deployment
  labels:
    app: retailer-app
    type: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retailer-app
      type: pod
  template:
    metadata:
      labels:
        app: retailer-app
        type: pod
    spec:
      containers:
        - name: retailer-application
          image: hitham/retailer-application:latest
          ports:
            - containerPort: 8080