apiVersion: v1
kind: Service
metadata:
  name: retailer-app-service
  labels:
    app: retailer-app
    type: service
spec:
  type: NodePort
  selector:
    app: retailer-app
    type: pod
  ports:
    - port: 8000
      targetPort: 8080
      nodePort: 30162
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retailer-app-ingress
  labels:
    app: retailer-app
    type: ingress
spec:
  ingressClassName: ingress-class-name
  rules:
    - host: retailer-app.com
      http:
        paths:
          - backend:
              service:
                name: retailer-app-service
                port:
                  number: 8000
            pathType: Prefix
            path: /